apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20231022032342.0.0+build.02e9424
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20231022032342.0.0+build.02e9424
  releaseNotes: |
    Release v20231022032342.0.0+build.02e9424 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-23-23-27-738339281/where-for-dinner-ui-my-apps-bundle@sha256:8d843fcf0d36a3992743559d2ee84b25b86e0a759012bc69d3924b05c2073c45
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

