apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231022032247.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231022032247.0.0+build.02e9424
  releaseNotes: |
    Release v20231022032247.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-23-23-27-738339281/where-for-dinner-my-apps-bundle@sha256:1ebaf4a6b8264da2975cdc7f9948baf5d7a2da4ccd02fe63b8c12ee31639d562
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

